services:
  - type: web
    name: frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: "./frontend/build"
    
  - type: web
    name: backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: node server.js